from modal_config import gr00t_image

with gr00t_image.imports():
    import numpy as np

# Unchunk the action chunk generated by gr00t model
def unchunk(action_chunk, action_plan, replan_steps):
    action_len = [v.shape[0] for v in action_chunk.values()]
    # Check if lengths are the same for every action generated
    if len(set(action_len)) != 1:
        raise ValueError(f"Inconsistent action lengths: {action_len}")
    # Check if action length is at least the value of replan_steps
    assert(action_len[0] >= replan_steps)

    keys = list(action_chunk.keys())
    
    # Just for debugging
    for k in keys:
        print(f"{k}: {action_chunk[k]}")

    for T in range(replan_steps):
        action_T = np.stack([action_chunk[k][T] for k in keys], axis=0)
        print(f"action_{T}: {action_T}")
        action_plan.append(action_T)
    return action_plan